# Generated by Django 5.2.5 on 2025-08-25 00:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('job_posting_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=500, unique=True)),
                ('company_name', models.CharField(db_index=True, max_length=200)),
                ('job_title', models.CharField(db_index=True, max_length=300)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('remote_ok', models.BooleanField(default=False)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scraping_success', models.BooleanField(default=True)),
                ('scraping_error', models.TextField(blank=True)),
                ('raw_json', models.JSONField(default=dict)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job_posting',
                'ordering': ['-scraped_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('job_application_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('saved', 'Saved for Later'), ('interested', 'Interested'), ('applied', 'Applied'), ('phone_screen', 'Phone Screen'), ('interview', 'Interview'), ('offer', 'Offer Received'), ('rejected', 'Rejected'), ('declined', 'Declined Offer')], default='saved', max_length=20)),
                ('applied_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('resume_version_used', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.jobposting')),
            ],
            options={
                'db_table': 'job_application',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['company_name', 'job_title'], name='job_posting_company_8ccde5_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['scraped_at'], name='job_posting_scraped_aaddcd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('user', 'job_posting')},
        ),
    ]
