# Generated by Django 5.2.5 on 2025-09-17 16:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobexperience'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('note_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('interview_notes', 'Interview Notes'), ('research', 'Research'), ('follow_up', 'Follow-up'), ('other', 'Other')], default='other', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(blank=True, help_text='Job this note relates to. Can be null for general notes.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='jobs.jobposting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job_note',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'job'], name='job_note_user_id_e3a72d_idx'), models.Index(fields=['user', 'category'], name='job_note_user_id_fa1734_idx'), models.Index(fields=['created_at'], name='job_note_created_bc602d_idx')],
            },
        ),
    ]
