# Generated by Django 5.2.5 on 2025-09-17 18:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='category',
            field=models.CharField(choices=[('interview_notes', 'Interview Notes'), ('interview_prep', 'Interview Prep'), ('research', 'Research'), ('follow_up', 'Follow-up'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.CreateModel(
            name='NoteTemplate',
            fields=[
                ('template_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('interview_notes', 'Interview Notes'), ('interview_prep', 'Interview Prep'), ('research', 'Research'), ('follow_up', 'Follow-up'), ('other', 'Other')], default='other', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'note_template',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'category'], name='note_templa_user_id_5ef982_idx'), models.Index(fields=['created_at'], name='note_templa_created_297f15_idx')],
            },
        ),
    ]
