# Generated by Django 5.2.5 on 2025-08-21 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
        migrations.AlterModelTable(
            name='usertoken',
            table='user_token',
        ),
    ]
