# Generated by Django 5.2.5 on 2025-08-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_table_alter_usertoken_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
