# Generated by Django 5.2.5 on 2025-09-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='title',
            field=models.CharField(blank=True, help_text='Auto-generated title based on conversation content', max_length=200, null=True),
        ),
    ]
