# Generated by Django 5.2.5 on 2025-08-26 22:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0003_alter_experience_education_and_more'),
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceSkill',
            fields=[
                ('experience_skill_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proficiency_demonstrated', models.CharField(blank=True, choices=[('Entry', 'Entry level'), ('Intermediate', 'Intermediate level'), ('Advanced', 'Advanced level'), ('Expert', 'Expert level'), ('Mastery', 'Mastery level')], help_text='Level of proficiency demonstrated in this specific experience', max_length=50, null=True)),
                ('prominence', models.CharField(choices=[('primary', 'Primary Skill - Central to the experience'), ('secondary', 'Secondary Skill - Important but not central'), ('supporting', 'Supporting Skill - Used but not prominent')], default='secondary', help_text='How prominently this skill featured in the experience', max_length=20)),
                ('usage_notes', models.TextField(blank=True, help_text='Specific notes about how this skill was applied in this experience')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('extraction_method', models.CharField(choices=[('manual', 'Manually Added'), ('auto_extracted', 'Automatically Extracted'), ('ai_suggested', 'AI Suggested')], default='manual', max_length=20)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experience.experience')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.skill')),
            ],
            options={
                'db_table': 'experience_skill',
                'indexes': [models.Index(fields=['experience', 'prominence'], name='experience__experie_73659f_idx'), models.Index(fields=['skill', 'proficiency_demonstrated'], name='experience__skill_i_87e713_idx')],
                'unique_together': {('experience', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='SkillAnalysis',
            fields=[
                ('analysis_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_experiences_analyzed', models.PositiveIntegerField()),
                ('total_jobs_analyzed', models.PositiveIntegerField()),
                ('total_skills_found', models.PositiveIntegerField()),
                ('new_skills_created', models.PositiveIntegerField(default=0)),
                ('total_skill_gaps', models.PositiveIntegerField()),
                ('average_job_match_score', models.FloatField(help_text='Average match percentage across all analyzed jobs')),
                ('highest_job_match_score', models.FloatField()),
                ('lowest_job_match_score', models.FloatField()),
                ('skill_gaps', models.JSONField(default=list, help_text='List of skill gaps found, ordered by priority')),
                ('job_matches', models.JSONField(default=list, help_text='Detailed job match analysis results')),
                ('skills_extracted', models.JSONField(default=list, help_text='List of new skills extracted from experiences')),
                ('analyzer_version', models.CharField(default='1.0', max_length=10)),
                ('analysis_parameters', models.JSONField(default=dict, help_text='Parameters used for this analysis run')),
                ('user_notes', models.TextField(blank=True, help_text="User's notes or observations about this analysis")),
                ('status', models.CharField(choices=[('fresh', 'Fresh Analysis'), ('in_progress', 'User Taking Action'), ('completed', 'User Addressed Gaps'), ('archived', 'Archived/Superseded')], default='fresh', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'skill_analysis',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='skill_analy_user_id_7ae3bc_idx'), models.Index(fields=['user', 'status'], name='skill_analy_user_id_79eee1_idx')],
            },
        ),
    ]
