# Generated by Django 5.2.5 on 2025-08-23 04:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0001_initial'),
        ('employment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('experience_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the experience')),
                ('experience_type', models.CharField(choices=[('project', 'Project'), ('achievement', 'Achievement'), ('responsibility', 'Responsibility'), ('certification', 'Certification'), ('award', 'Award'), ('presentation', 'Presentation'), ('publication', 'Publication'), ('volunteer', 'Volunteer Work'), ('other', 'Other')], default='project', max_length=20)),
                ('date_started', models.DateField(blank=True, null=True)),
                ('date_finished', models.DateField(blank=True, null=True)),
                ('skills_used', models.JSONField(blank=True, default=list, help_text='List of skills/technologies used')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags for categorizing and filtering')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('visibility', models.CharField(choices=[('public', 'Include in Resumes'), ('private', 'Personal Reference Only'), ('draft', 'Draft - Not Ready')], default='public', max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='education.education')),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='employment.employment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_started', '-created_date'],
                'indexes': [models.Index(fields=['user', 'visibility'], name='experience__user_id_0726a8_idx'), models.Index(fields=['user', 'experience_type'], name='experience__user_id_06a329_idx'), models.Index(fields=['employment'], name='experience__employm_98bdfc_idx'), models.Index(fields=['education'], name='experience__educati_9bd730_idx')],
            },
        ),
    ]
