# Generated by Django 5.2.5 on 2025-08-23 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='experience',
            new_name='experience_user_id_097d4a_idx',
            old_name='experience__user_id_0726a8_idx',
        ),
        migrations.RenameIndex(
            model_name='experience',
            new_name='experience_user_id_9e922a_idx',
            old_name='experience__user_id_06a329_idx',
        ),
        migrations.RenameIndex(
            model_name='experience',
            new_name='experience_employm_4b6503_idx',
            old_name='experience__employm_98bdfc_idx',
        ),
        migrations.RenameIndex(
            model_name='experience',
            new_name='experience_educati_77dbcc_idx',
            old_name='experience__educati_9bd730_idx',
        ),
        migrations.AlterModelTable(
            name='experience',
            table='experience',
        ),
    ]
