# Generated by Django 5.2.5 on 2025-08-24 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
        ('employment', '0001_initial'),
        ('experience', '0002_rename_experience__user_id_0726a8_idx_experience_user_id_097d4a_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='education.education'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='employment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='employment.employment'),
        ),
    ]
