# Generated by Django 5.2.5 on 2025-08-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0003_alter_experience_education_and_more'),
        ('skills', '0002_experienceskill_skillanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='skills',
            field=models.ManyToManyField(blank=True, help_text='Skills demonstrated in this experience', related_name='experiences', through='skills.ExperienceSkill', to='skills.skill'),
        ),
    ]
