# Generated by Django 5.2.5 on 2025-09-10 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
        ('education', '0001_initial'),
        ('employment', '0001_initial'),
        ('experience', '0004_experience_skills'),
        ('skills', '0002_experienceskill_skillanalysis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiences', to='conversation.conversation'),
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['conversation'], name='experience_convers_356e30_idx'),
        ),
    ]
